//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityBag
{
    using System;
    using System.Collections.Generic;
    
    public partial class file
    {
        public int Id { get; set; }
        public string username { get; set; }
        public string iv { get; set; }
        public string namefile { get; set; }
        public string time { get; set; }
        public string date { get; set; }
        public string hash { get; set; }
    }
}
